/**
 * 改訂版 PRD のエクスポート機能。
 *
 * Specify 上で「決定済み」になった項目を反映した Markdown を生成し、
 * ダウンロード（Blob → object URL）またはクリップボードコピーで配布する。
 *
 * Notion 実 API は使わない: secret 管理 + 配信先設定が必要で demo の本筋から外れるため、
 * 「Notion で貼り付ける用の Markdown をクリップボードに」のシンプルな運用にする。
 * Notion は Markdown 貼り付けで適切に変換される (見出し・リスト・引用ブロック等)。
 */

import type { Result } from "./types";

export interface DecisionStateForExport {
  selectedOption: string | null;
  memo: string;
  decided: boolean;
}

/** 改訂版 PRD の Markdown を生成。 */
export function generateMarkdown(
  result: Result,
  decisionStates: Record<number, DecisionStateForExport>,
  prdLabel: string,
): string {
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;

  const lines: string[] = [];

  // ヘッダ
  lines.push(`# 改訂版 PRD: ${prdLabel || "PRD"}`);
  lines.push("");
  lines.push(
    "> Specify が抽出した「決めるべきこと」に対して、決定内容を反映した改訂版です。",
  );
  lines.push("");
  lines.push("## サマリ");
  lines.push("");
  lines.push(result.summary || "(なし)");
  lines.push("");

  // 決定済み項目
  const decided = result.decisions
    .map((d, i) => ({ d, i, s: decisionStates[i] }))
    .filter(({ s }) => s?.decided && s?.selectedOption);

  if (decided.length > 0) {
    lines.push("## 決定済みの項目");
    lines.push("");
    for (const { d, s } of decided) {
      lines.push(`### ${d.title}`);
      lines.push("");
      lines.push(`- **優先度**: ${priorityLabel(d.priority)}`);
      lines.push(`- **カテゴリ**: ${d.category}`);
      lines.push(`- **決定**: ${s!.selectedOption}`);
      if (s!.memo.trim()) {
        lines.push(`- **メモ**: ${s!.memo.trim()}`);
      }
      lines.push(`- **理由**: ${d.rationale}`);
      lines.push(`- **検討した選択肢**: ${d.options.join(" / ")}`);
      lines.push("");
    }
  }

  // 未決定項目（参考）
  const undecided = result.decisions
    .map((d, i) => ({ d, s: decisionStates[i] }))
    .filter(({ s }) => !s?.decided);

  if (undecided.length > 0) {
    lines.push("## 未決定の項目（要検討）");
    lines.push("");
    for (const { d } of undecided) {
      lines.push(`- **${d.title}** (${priorityLabel(d.priority)} / ${d.category})`);
      lines.push(`  - 選択肢: ${d.options.join(" / ")}`);
      lines.push(`  - 理由: ${d.rationale}`);
    }
    lines.push("");
  }

  // 過去 PRD との矛盾
  if (result.contradictions.length > 0) {
    lines.push("## 過去 PRD との矛盾（参考）");
    lines.push("");
    for (const c of result.contradictions) {
      lines.push(`### ${c.title}`);
      lines.push("");
      lines.push(`- **優先度**: ${priorityLabel(c.priority)}`);
      lines.push(`- **過去 PRD ID**: \`${c.past_prd_id}\``);
      lines.push(`- **過去 PRD の記述**: ${c.past_prd_quote}`);
      lines.push(`- **新 PRD の記述**: ${c.new_prd_quote}`);
      lines.push(`- **指摘**: ${c.rationale}`);
      lines.push("");
    }
  }

  // 縮退情報
  if (result.meta.failed_agents.length > 0) {
    lines.push("## 注: 縮退動作中");
    lines.push("");
    for (const f of result.meta.failed_agents) {
      lines.push(`- ${f}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Specify on ${dateStr}*`);

  return lines.join("\n");
}

/** Markdown 文字列を .md ファイルとしてダウンロードさせる。 */
export function downloadMarkdown(filename: string, content: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // ブラウザに URL を回収させる（即時 revoke だと Safari でダウンロード失敗する事例あり、tick 後に）。
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Markdown 文字列をクリップボードにコピー。返り値は成功/失敗の Promise。 */
export async function copyMarkdownToClipboard(content: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch {
    return false;
  }
}

function priorityLabel(p: string): string {
  if (p === "must") return "必須";
  if (p === "should") return "推奨";
  if (p === "nice") return "任意";
  return p;
}
